/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Auditor;
import service.AuditorService;

/**
 *
 * @author Celia
 */
public class AuditorDashboard extends javax.swing.JFrame {
    DefaultTableModel tableModel = new DefaultTableModel(); 

    /**
     * Creates new form AuditorDashboard
     */
    public AuditorDashboard() {
        initComponents();
        addData();
    }
    
//    public void addData(){
//         try {
//            Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",6000);
//           AuditorService service = (AuditorService) theRegistry.lookup("auditor");
//            Auditor theAuditor = new Auditor();
//            DefaultTableModel tm=(DefaultTableModel)auditorTable.getModel();
//            List<Auditor> audObj = service.allAuditor();
//              tableModel.setRowCount(0);
//              if(audObj!=null){
//           for(Auditor theAud: audObj){
//              Object data[]={
//                  String.valueOf(theAud.getId()),
//                  theAud.getFullnames(),
//                  theAud.getGender(),
//                  theAud.getBirth_date(),
//                  theAud.getPhoneNumber(),
//                  theAud.getBranch(),
//                  //theAud.getMaterials(),
//                  theAud.getStartedDate()
//              };
//              tm.addRow(data);
//              
//           }}else{
//                  JOptionPane.showMessageDialog(this, "no data found");
//              }
//              
//         } catch (Exception e) {
//             e.printStackTrace();
//         }
//     }
    
    public void addData() {
    try {
        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        AuditorService service = (AuditorService) theRegistry.lookup("auditor");
        Auditor theAuditor = new Auditor();
        DefaultTableModel tm = (DefaultTableModel) auditorTable.getModel();

        // Clear existing rows in the table
        tm.setRowCount(0);

        // Get the search ID from the text field
        String searchId = searchIdTxt.getText().trim();

        // Check if the search ID is not empty
        if (!searchId.isEmpty()) {
            // Create a new Auditor object with the specified ID
            theAuditor.setId(Integer.parseInt(searchId));

            // Use the searchAuditor method to retrieve the Auditor
            Auditor searchedAuditor = service.searchAuditor(theAuditor);

            // Check if the searchedAuditor is not null
            if (searchedAuditor != null) {
                Object data[] = {
                        String.valueOf(searchedAuditor.getId()),
                        searchedAuditor.getFullnames(),
                        searchedAuditor.getGender(),
                        searchedAuditor.getBirth_date(),
                        searchedAuditor.getPhoneNumber(),
                        searchedAuditor.getBranch(),
                        //searchedAuditor.getMaterials(),
                        searchedAuditor.getStartedDate()
                };
                tm.addRow(data);
            } else {
                JOptionPane.showMessageDialog(this, "No data found for ID: " + searchId);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter an ID for search");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        searchIdTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        auditorTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchIdTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Mongolian Baiti", 1, 20)); // NOI18N
        jLabel11.setText("Search by your ID:");

        searchBtn.setBackground(new java.awt.Color(0, 153, 0));
        searchBtn.setFont(new java.awt.Font("Mongolian Baiti", 1, 20)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        auditorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Auditor ID", "Auditor Name", "Gender", "Date of Birth", "Phone Number", "Branch Name", "Started Date"
            }
        ));
        jScrollPane2.setViewportView(auditorTable);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setText("Auditor's Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27)
                                .addComponent(searchIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel1)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(8, 8, 8)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
//        try {
//
//            Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",6000);
//            AuditorService service =(AuditorService) theRegistry.lookup("auditor");
//            Auditor theAuditor = new Auditor();
//            theAuditor.setId(Integer.parseInt(searchIdTxt.getText()));
//            Auditor audObj = service.searchAuditor(theAuditor);
//            if (audObj != null) {
//                idTxt.setText(String.valueOf(audObj.getId()));
//                namesTxt.setText(audObj.getFullnames());
//                branchCombo.setSelectedItem(audObj.getBranch());
//                GenderCombo.setSelectedItem(audObj.getGender());
//                phonenbrTxt.setText(audObj.getPhoneNumber());
//                //dobTxt.setDate(audObj.getBirth_date());
//                
//                //dobTxt.setDateFormatString(audObj.getBirth_date());
//             
//               // materialList.setSelectedValue(theObj.getStock());
//            } else {
//                JOptionPane.showMessageDialog(this, "Data not found");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//       
//        DefaultTableModel dft = (DefaultTableModel) auditorTable.getModel();
//        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dft);
//
//        sorter.setRowFilter(RowFilter.regexFilter(searchIdTxt.getText()));
//
//        auditorTable.setRowSorter(sorter);
        addData();
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuditorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuditorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuditorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuditorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuditorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable auditorTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchIdTxt;
    // End of variables declaration//GEN-END:variables
}
